### ISSUE TITLE
Rename repo to "MRVN-VMT" to match rest of GitHub organisation's repos

### ISSUE THREAD

**Issue by snake-biscuits** [MRVN-radiant/MRVN-vmt#1]
Looks like when I transferred MRVN-vmt from myself to the org I lost access to settings.
@F1F7Y you might be able to rename, but I can't

**Comment by F1F7Y** [comment]
> Looks like when I transferred MRVN-vmt from myself to the org I lost access to settings. @F1F7Y you might be able to rename, but I can't

Made you an owner so you should have the same access as I do. Github perms are funky so test it out :+1:

**Comment by F1F7Y** [comment]
Would also be cool if you had 2FA, but Im not going to force you :)
![image](https://user-images.githubusercontent.com/64418963/220888228-da5bba0a-ff26-4379-828e-5027ce9f3204.png)

**Comment by snake-biscuits** [comment]
All sorted now, I'll look into setting up 2FA later probably
